ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: ${PORT}
        watch:
          - classes
postgres:
  url:  ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}